### ISSUE TITLE
rule dependencies

### ISSUE THREAD

**Issue by gfudenberg** [open2c/quaich#6]
I tried creating a config that only calculates dots by turning all the do: statements to False except for the dots rules & get the following KeyError-- any guesses what might be going on?
```
(quaich) [fudenber@endeavour1 quaich]$ snakemake --use-conda --configfile config/config-reduced2.yml -n 
KeyError in line 176 of /project/fudenber_735/quaich_process/quaich/workflow/Snakefile: 'bed_pairs' File "/project/fudenber_735/quaich_process/quaich/workflow/Snakefile", line 176, in <module>
```
this error seems to resolve if I turn on everything in pileup.

Q:. does the expected calculation need to be moved around somehow in the snakefile?

**Comment by Phlya** [comment]
This was a small bug, should be fixed now!

**Comment by Phlya** [comment]
What do you mean by moving expected calculation? Why?

**Comment by gfudenberg** [comment]
If I understood the log,  it looked like expected was being calculated at a few different places in the script, and not just once at the beginning. Could be missing something though!

**Comment by Phlya** [comment]
Maybe it was different resolutions?..

**Comment by gfudenberg** [comment]
It was in completely different parts of the log if I recall

**Comment by Phlya** [comment]
I think it's probably different resolutions, the order of rule execution is random, and it can decide to do it at different times in the process. But please share a log if you notice anything weird another time.

**Comment by Phlya** [comment]
I think we discussed it and there is no issue after all? Closing for now.
